---
title: "summary_stats Comp session 5A"
author: "Nikhil D."
date: "10/20/2021"
output:  
  html_document:
    keep_md: true
---

```{r, echo=FALSE,results='hide',message=FALSE,warning=FALSE,include=TRUE}

# messing rmd code chunk options (see above)
library(tidyverse)

head(starwars)

dim(starwars)

# graph of character height vs mass
ggplot(data = starwars,aes(x=height,y=mass,color=mass))+
  geom_point(size=4,alpha=0.7)+
  xlab('Height (cm)')+
  ylab('Mass/Weight (kg)')+
  ggtitle("Star Wars Character Height vs Mass/Weight")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r, echo=TRUE,results='hide',message=FALSE,warning=FALSE,include=TRUE}

# histogram of character heights
ggplot(data = starwars, aes(x = height)) +
  geom_histogram(color = "red", fill = "purple")+
  xlab('Height (cm)')+
  ylab('Count')+
  ggtitle("Star Wars Character Heights (cm)")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}

# mean median, variance, and standard deviation (drop NA values)

sw_height_mean <- mean(starwars$height,na.rm = TRUE)

sw_height_median <- median(starwars$height,na.rm = TRUE)

sw_height_variance <- var(starwars$height,na.rm = TRUE)

sw_height_sd <- sd(starwars$height,na.rm = TRUE)



```

There is a mean height of **`r round(sw_height_mean,1)`** centimeters in the characters of star wars dataframe